apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-7kcg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0061-tenant/tkrw-pr712-0075-0061-app/devfile-sample-7kcg@sha256:19d154c0b50f6eb329cbbef578cb8872aebdd54dce6b7f1b88e8b7b673fceee6
        name: my-nodejs
        resources: {}
status: {}
